/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IDataLiquidityPool {
  export type FileResponseStruct = {
    fileId: BigNumberish;
    timestamp: BigNumberish;
    proofIndex: BigNumberish;
    rewardAmount: BigNumberish;
  };

  export type FileResponseStructOutput = [
    fileId: bigint,
    timestamp: bigint,
    proofIndex: bigint,
    rewardAmount: bigint
  ] & {
    fileId: bigint;
    timestamp: bigint;
    proofIndex: bigint;
    rewardAmount: bigint;
  };

  export type ContributorInfoResponseStruct = {
    contributorAddress: AddressLike;
    filesListCount: BigNumberish;
  };

  export type ContributorInfoResponseStructOutput = [
    contributorAddress: string,
    filesListCount: bigint
  ] & { contributorAddress: string; filesListCount: bigint };
}

export declare namespace DataLiquidityPoolImplementation {
  export type InitParamsStruct = {
    trustedForwarder: AddressLike;
    ownerAddress: AddressLike;
    tokenAddress: AddressLike;
    dataRegistryAddress: AddressLike;
    teePoolAddress: AddressLike;
    name: string;
    publicKey: string;
    proofInstruction: string;
    fileRewardFactor: BigNumberish;
  };

  export type InitParamsStructOutput = [
    trustedForwarder: string,
    ownerAddress: string,
    tokenAddress: string,
    dataRegistryAddress: string,
    teePoolAddress: string,
    name: string,
    publicKey: string,
    proofInstruction: string,
    fileRewardFactor: bigint
  ] & {
    trustedForwarder: string;
    ownerAddress: string;
    tokenAddress: string;
    dataRegistryAddress: string;
    teePoolAddress: string;
    name: string;
    publicKey: string;
    proofInstruction: string;
    fileRewardFactor: bigint;
  };
}

export interface DataLiquidityPoolImplementationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "MAINTAINER_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "addRewardsForContributors"
      | "contributorFiles"
      | "contributorInfo"
      | "contributors"
      | "contributorsCount"
      | "dataRegistry"
      | "fileRewardFactor"
      | "files"
      | "filesListAt"
      | "filesListCount"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "isTrustedForwarder"
      | "multicall"
      | "name"
      | "pause"
      | "paused"
      | "proofInstruction"
      | "proxiableUUID"
      | "publicKey"
      | "renounceRole"
      | "requestReward"
      | "revokeRole"
      | "supportsInterface"
      | "teePool"
      | "token"
      | "totalContributorsRewardAmount"
      | "trustedForwarder"
      | "unpause"
      | "updateFileRewardFactor"
      | "updateProofInstruction"
      | "updatePublicKey"
      | "updateTeePool"
      | "updateTrustedForwarder"
      | "upgradeToAndCall"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FileInvalidated"
      | "FileRewardFactorUpdated"
      | "FileValidated"
      | "Initialized"
      | "Paused"
      | "ProofInstructionUpdated"
      | "PublicKeyUpdated"
      | "RewardRequested"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TeePoolUpdated"
      | "Unpaused"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAINTAINER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addRewardsForContributors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributorFiles",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributorInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contributors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributorsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dataRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fileRewardFactor",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "files", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "filesListAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "filesListCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [DataLiquidityPoolImplementation.InitParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proofInstruction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "publicKey", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestReward",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "teePool", values?: undefined): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalContributorsRewardAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "trustedForwarder",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateFileRewardFactor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProofInstruction",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePublicKey",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTeePool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTrustedForwarder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAINTAINER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addRewardsForContributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorFiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dataRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fileRewardFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "files", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "filesListAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "filesListCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proofInstruction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "publicKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "teePool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalContributorsRewardAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateFileRewardFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProofInstruction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTeePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace FileInvalidatedEvent {
  export type InputTuple = [fileId: BigNumberish];
  export type OutputTuple = [fileId: bigint];
  export interface OutputObject {
    fileId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileRewardFactorUpdatedEvent {
  export type InputTuple = [newFileRewardFactor: BigNumberish];
  export type OutputTuple = [newFileRewardFactor: bigint];
  export interface OutputObject {
    newFileRewardFactor: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileValidatedEvent {
  export type InputTuple = [fileId: BigNumberish];
  export type OutputTuple = [fileId: bigint];
  export interface OutputObject {
    fileId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofInstructionUpdatedEvent {
  export type InputTuple = [newProofInstruction: string];
  export type OutputTuple = [newProofInstruction: string];
  export interface OutputObject {
    newProofInstruction: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicKeyUpdatedEvent {
  export type InputTuple = [newPublicKey: string];
  export type OutputTuple = [newPublicKey: string];
  export interface OutputObject {
    newPublicKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardRequestedEvent {
  export type InputTuple = [
    contributorAddress: AddressLike,
    fileId: BigNumberish,
    proofIndex: BigNumberish,
    rewardAmount: BigNumberish
  ];
  export type OutputTuple = [
    contributorAddress: string,
    fileId: bigint,
    proofIndex: bigint,
    rewardAmount: bigint
  ];
  export interface OutputObject {
    contributorAddress: string;
    fileId: bigint;
    proofIndex: bigint;
    rewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TeePoolUpdatedEvent {
  export type InputTuple = [newTeePool: AddressLike];
  export type OutputTuple = [newTeePool: string];
  export interface OutputObject {
    newTeePool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DataLiquidityPoolImplementation extends BaseContract {
  connect(runner?: ContractRunner | null): DataLiquidityPoolImplementation;
  waitForDeployment(): Promise<this>;

  interface: DataLiquidityPoolImplementationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAINTAINER_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  addRewardsForContributors: TypedContractMethod<
    [contributorsRewardAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  contributorFiles: TypedContractMethod<
    [contributorAddress: AddressLike, index: BigNumberish],
    [IDataLiquidityPool.FileResponseStructOutput],
    "view"
  >;

  contributorInfo: TypedContractMethod<
    [contributorAddress: AddressLike],
    [IDataLiquidityPool.ContributorInfoResponseStructOutput],
    "view"
  >;

  contributors: TypedContractMethod<
    [index: BigNumberish],
    [IDataLiquidityPool.ContributorInfoResponseStructOutput],
    "view"
  >;

  contributorsCount: TypedContractMethod<[], [bigint], "view">;

  dataRegistry: TypedContractMethod<[], [string], "view">;

  fileRewardFactor: TypedContractMethod<[], [bigint], "view">;

  files: TypedContractMethod<
    [fileId: BigNumberish],
    [IDataLiquidityPool.FileResponseStructOutput],
    "view"
  >;

  filesListAt: TypedContractMethod<[index: BigNumberish], [bigint], "view">;

  filesListCount: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [params: DataLiquidityPoolImplementation.InitParamsStruct],
    [void],
    "nonpayable"
  >;

  isTrustedForwarder: TypedContractMethod<
    [forwarder: AddressLike],
    [boolean],
    "view"
  >;

  multicall: TypedContractMethod<[data: BytesLike[]], [string[]], "nonpayable">;

  name: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  proofInstruction: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  publicKey: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestReward: TypedContractMethod<
    [fileId: BigNumberish, proofIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  teePool: TypedContractMethod<[], [string], "view">;

  token: TypedContractMethod<[], [string], "view">;

  totalContributorsRewardAmount: TypedContractMethod<[], [bigint], "view">;

  trustedForwarder: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateFileRewardFactor: TypedContractMethod<
    [newFileRewardFactor: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateProofInstruction: TypedContractMethod<
    [newProofInstruction: string],
    [void],
    "nonpayable"
  >;

  updatePublicKey: TypedContractMethod<
    [newPublicKey: string],
    [void],
    "nonpayable"
  >;

  updateTeePool: TypedContractMethod<
    [newTeePool: AddressLike],
    [void],
    "nonpayable"
  >;

  updateTrustedForwarder: TypedContractMethod<
    [trustedForwarderAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAINTAINER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addRewardsForContributors"
  ): TypedContractMethod<
    [contributorsRewardAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contributorFiles"
  ): TypedContractMethod<
    [contributorAddress: AddressLike, index: BigNumberish],
    [IDataLiquidityPool.FileResponseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "contributorInfo"
  ): TypedContractMethod<
    [contributorAddress: AddressLike],
    [IDataLiquidityPool.ContributorInfoResponseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "contributors"
  ): TypedContractMethod<
    [index: BigNumberish],
    [IDataLiquidityPool.ContributorInfoResponseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "contributorsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dataRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fileRewardFactor"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "files"
  ): TypedContractMethod<
    [fileId: BigNumberish],
    [IDataLiquidityPool.FileResponseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "filesListAt"
  ): TypedContractMethod<[index: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "filesListCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [params: DataLiquidityPoolImplementation.InitParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isTrustedForwarder"
  ): TypedContractMethod<[forwarder: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "multicall"
  ): TypedContractMethod<[data: BytesLike[]], [string[]], "nonpayable">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "proofInstruction"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publicKey"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestReward"
  ): TypedContractMethod<
    [fileId: BigNumberish, proofIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "teePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalContributorsRewardAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "trustedForwarder"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFileRewardFactor"
  ): TypedContractMethod<
    [newFileRewardFactor: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateProofInstruction"
  ): TypedContractMethod<[newProofInstruction: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePublicKey"
  ): TypedContractMethod<[newPublicKey: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTeePool"
  ): TypedContractMethod<[newTeePool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTrustedForwarder"
  ): TypedContractMethod<
    [trustedForwarderAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "FileInvalidated"
  ): TypedContractEvent<
    FileInvalidatedEvent.InputTuple,
    FileInvalidatedEvent.OutputTuple,
    FileInvalidatedEvent.OutputObject
  >;
  getEvent(
    key: "FileRewardFactorUpdated"
  ): TypedContractEvent<
    FileRewardFactorUpdatedEvent.InputTuple,
    FileRewardFactorUpdatedEvent.OutputTuple,
    FileRewardFactorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FileValidated"
  ): TypedContractEvent<
    FileValidatedEvent.InputTuple,
    FileValidatedEvent.OutputTuple,
    FileValidatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProofInstructionUpdated"
  ): TypedContractEvent<
    ProofInstructionUpdatedEvent.InputTuple,
    ProofInstructionUpdatedEvent.OutputTuple,
    ProofInstructionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PublicKeyUpdated"
  ): TypedContractEvent<
    PublicKeyUpdatedEvent.InputTuple,
    PublicKeyUpdatedEvent.OutputTuple,
    PublicKeyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardRequested"
  ): TypedContractEvent<
    RewardRequestedEvent.InputTuple,
    RewardRequestedEvent.OutputTuple,
    RewardRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TeePoolUpdated"
  ): TypedContractEvent<
    TeePoolUpdatedEvent.InputTuple,
    TeePoolUpdatedEvent.OutputTuple,
    TeePoolUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "FileInvalidated(uint256)": TypedContractEvent<
      FileInvalidatedEvent.InputTuple,
      FileInvalidatedEvent.OutputTuple,
      FileInvalidatedEvent.OutputObject
    >;
    FileInvalidated: TypedContractEvent<
      FileInvalidatedEvent.InputTuple,
      FileInvalidatedEvent.OutputTuple,
      FileInvalidatedEvent.OutputObject
    >;

    "FileRewardFactorUpdated(uint256)": TypedContractEvent<
      FileRewardFactorUpdatedEvent.InputTuple,
      FileRewardFactorUpdatedEvent.OutputTuple,
      FileRewardFactorUpdatedEvent.OutputObject
    >;
    FileRewardFactorUpdated: TypedContractEvent<
      FileRewardFactorUpdatedEvent.InputTuple,
      FileRewardFactorUpdatedEvent.OutputTuple,
      FileRewardFactorUpdatedEvent.OutputObject
    >;

    "FileValidated(uint256)": TypedContractEvent<
      FileValidatedEvent.InputTuple,
      FileValidatedEvent.OutputTuple,
      FileValidatedEvent.OutputObject
    >;
    FileValidated: TypedContractEvent<
      FileValidatedEvent.InputTuple,
      FileValidatedEvent.OutputTuple,
      FileValidatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProofInstructionUpdated(string)": TypedContractEvent<
      ProofInstructionUpdatedEvent.InputTuple,
      ProofInstructionUpdatedEvent.OutputTuple,
      ProofInstructionUpdatedEvent.OutputObject
    >;
    ProofInstructionUpdated: TypedContractEvent<
      ProofInstructionUpdatedEvent.InputTuple,
      ProofInstructionUpdatedEvent.OutputTuple,
      ProofInstructionUpdatedEvent.OutputObject
    >;

    "PublicKeyUpdated(string)": TypedContractEvent<
      PublicKeyUpdatedEvent.InputTuple,
      PublicKeyUpdatedEvent.OutputTuple,
      PublicKeyUpdatedEvent.OutputObject
    >;
    PublicKeyUpdated: TypedContractEvent<
      PublicKeyUpdatedEvent.InputTuple,
      PublicKeyUpdatedEvent.OutputTuple,
      PublicKeyUpdatedEvent.OutputObject
    >;

    "RewardRequested(address,uint256,uint256,uint256)": TypedContractEvent<
      RewardRequestedEvent.InputTuple,
      RewardRequestedEvent.OutputTuple,
      RewardRequestedEvent.OutputObject
    >;
    RewardRequested: TypedContractEvent<
      RewardRequestedEvent.InputTuple,
      RewardRequestedEvent.OutputTuple,
      RewardRequestedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TeePoolUpdated(address)": TypedContractEvent<
      TeePoolUpdatedEvent.InputTuple,
      TeePoolUpdatedEvent.OutputTuple,
      TeePoolUpdatedEvent.OutputObject
    >;
    TeePoolUpdated: TypedContractEvent<
      TeePoolUpdatedEvent.InputTuple,
      TeePoolUpdatedEvent.OutputTuple,
      TeePoolUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
